service: deno-serverless
frameworkVersion: ">=1.1.0 <2.0.0"

package:
  exclude:
    - .deno_dir/gen/file
    - node_modules
    - package-lock.json

provider:
  name: aws
  runtime: provided
  stage: dev
  region: ${env:AWS_DEFAULT_REGION, 'us-west-2'}

functions:
  hello-world:
    handler: hello-world.handler
    layers:
      - !GetAtt Deno.Outputs.LayerArn
    memorySize: 128
    description: DENO Hello World! With Serverless
    events:
      - http:
          path: /
          method: get

resources:
  Transform: AWS::Serverless-2016-10-31
  Resources:
    Deno:
      Type: AWS::Serverless::Application
      Properties:
        Location:
          ApplicationId: arn:aws:serverlessrepo:us-east-1:390065572566:applications/deno
          SemanticVersion: 1.0.2

plugins:
  - serverless-scriptable-plugin

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: DENO_DIR=.deno_dir deno cache hello-world.ts && cp -R .deno_dir/gen/file/$PWD/ .deno_dir/LAMBDA_TASK_ROOT
